export const welcomeMessage = '#customer_menu_top'
export const addressBookContacts = '.dash-tile-ocean .dash-tile-text'
export const orderHistory = '.dash-tile-flower .dash-tile-text'
export const downloads = '.dash-tile-oil .dash-tile-text'
export const transactionHistory = '.dash-tile-balloon .dash-tile-text'
